<?php 

function cipher_menu() {
	$items['cipher'] = array(
		'title'=> 'Encrypt Phrase',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cipher_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	$items['success'] = array(
		'title' => 'Success',
		'page callback' => 'cipher_success',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function cipher_form() {
	$form['shift_value'] = array(
		'#title' => 'Shift Value',
		'#type' => 'textfield',
		'#description' => t('Please enter your numerical shift value'),
		'#element_validate' => array('element_validate_integer_positive'),
		'#required' => TRUE,
	);

	$form['shift_direction'] = array(
		'#title' => 'Shift Direction',
		'#type' => 'textfield',
		'#description' => t('Please enter the direction of the shift cipher, i.e., Right or Left'),
		'#element_validate' => array('element_validate_direction'),
		'#required' => TRUE,
	);

	$form['input_phrase'] = array(
		'#title' => 'Input Phrase',
		'#type' => 'textfield',
		'#description' => t('Please enter a phrase that you would like to be encrypted'),
		'#element_validate' => array('element_validate_input_phrase'),
		'#required' => TRUE,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Encrypt Phrase',
	);
	return $form;
}

function element_validate_direction($element) {
	if ($element['#value'] != "left" || "Left" || "right" || "Right") {
		form_error($element, t('Direction entered must be right or left'));
	}
}

function element_validate_input_phrase($element) {
	// If anything but letters and spaces are found in the array, then return error message
	$input_phrase_array = $element['#value'];
	$exceptions = array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "!", "@", "#", "$", "%");
	$exploded_words = explode(" ", $element['#value']);
	$exploded_characters = explode("", $exploded_words);

	foreach($exploded_characters as $character)
        {
                if (in_array($character, $exceptions))
                {
                    form_error($element, t('Please enter a word only, no numbers or special characters'));

                } else {
                	return //input values in encrypyted form
                }
             }
         }

}


function cipher_form_submit($form, &$form_state) {
	// $shift_value = $form_state['values']['shift_value'];
	// $shift_direction = $form_state['values']['shift_direction'];
	// $input_phrase = $form_state['values']['input_phrase'];

	$_SESSION[]
	//Store the results of the shift ciphon here?

	$form_state['redirect'] = 'success';
}

function cipher_success() {
	//Return the results of the shift ciphon here?
}




















