<?php 

function cipher_menu() {
	$items['cipher'] = array(
		'title'=> 'Encrypt Phrase',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cipher_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	$items['success'] = array(
		'title' => 'Success',
		'page callback' => 'cipher_success',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function cipher_form() {
	$form['shift_value'] = array(
		'#title' => 'Shift direction',
		'#type' => 'textfield',
		'#description' => t('Please enter your numerical shift value'),
		'#element_validate' => array('element_validate_integer_positive'),
		'#required' => TRUE,
	);

	$form['shift_direction'] = array(
		'#title' => 'Shift Direction',
		'#type' => 'textfield',
		'#description' => t('Please enter the direction of the shift cipher, i.e., Right or Left'),
		'#element_validate' => array('element_validate_direction'),
		'#required' => TRUE,
	);

	$form['input_phrase'] = array(
		'#title' => 'Input Phrase',
		'#type' => 'textfield',
		'#description' => t('Please enter a phrase that you would like to be encrypted'),
		'#element_validate' => array('element_validate_input_phrase'),
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Encrypt Phrase',
	);
	return $form;
}






















