<?php 

function cipher_menu() {
	$items['cipher'] = array(
		'title'=> 'Encrypt Phrase',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cipher_form'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	$items['success'] = array(
		'title' => 'Success',
		'page callback' => 'cipher_success',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function cipher_form() {
	$form['shift_value'] = array(
		'#title' => 'Shift direction',
		'#type' => 'textfield',
		'#description' => t('Please enter your numerical shift value'),
		'#element_validate' => array('element_validate_integer_positive'),
		'#required' => TRUE,
	);
	$form['shift_direction'] = array(
		
	);
}






















